### ISSUE TITLE
after install "The Journal" theme looks nothing like Marketplace version

### ISSUE THREAD

**Issue by mcarter960** [TryGhost/Themes#123] opened 2022-06-11 17:54 UTC
not sure what i am missing here, Installing "The Journal" theme looks nothing like Marketplace version.

author page does not work, etc...

Is there a detailed config HOWTO?

thank you

**Comment by minimaluminium** [comment] 2022-07-04 08:18
Duplicate of https://github.com/TryGhost/Journal/issues/6

**Closed by minimaluminium** 2022-07-04 08:18 UTC
