### ISSUE TITLE
[Wave] Incorrect image order in post.

### ISSUE THREAD

**Issue by pearcemichal** [TryGhost/Themes#141] opened 2022-07-13 16:11 UTC
Ghost version: 5.3.1 (latest)
Server: localhost

When I create or edit a post by copying and pasting from google images, the images in the post on the site are in a different order than the images in the editor, when using the Wave theme. 

![image](https://user-images.githubusercontent.com/29542619/178779285-755d88ed-6119-465d-a257-91c231881fbf.png)

The post editor still shows the images correctly. I can try and fix them, but this just makes the images on the post shift around at random. 

I originally found this issue in my own custom theme that I created using Wave as a base, but I tried loading the base Wave theme, and the issue is still present. 

the issue does not seem to occur on the default casper theme. 

I don't remember this happening when I was using ghost 5.2, so is it possible something in the 5.3 update broke this theme?

**Comment by minimaluminium** [comment] 2022-10-06 07:26
Hey @pearcemichal,

I couldn't reproduce this. Would you be able to send me an URL to the post?

**Comment by minimaluminium** [comment] 2022-11-02 08:21
Closing this for now.

**Closed by minimaluminium** 2022-11-02 08:21 UTC
